[pytest]
addopts = -W ignore::pytest.PytestAssertRewriteWarning
filterwarnings =
    ignore:Module already imported so cannot be rewritten; anyio:pytest.PytestAssertRewriteWarning
    ignore:.*crypt.*is deprecated.*Python 3\.13.*:DeprecationWarning
