from typing import Dict


def get_index_context() -> Dict[str, object]:
    return {
        "masthead_stats": [
            {"value": "6", "label": "Eras históricas"},
            {"value": "72", "label": "Retos verificados"},
            {"value": "100%", "label": "Gratuito para empezar"},
        ],
        "data_strip": [
            {"value": "6 Eras", "label": "De Prehistoria a Modernidad"},
            {"value": "72 Retos", "label": "Contenido académico verificado"},
            {"value": "100%", "label": "Rigor académico verificado"},
        ],
        "eras": [
            {
                "number": "I",
                "title": "Prehistoria",
                "caption": "Fig. 1 — Monumentos megalíticos, Neolítico tardío, c. 3000 a.C.",
                "description": "Paleolítico, Neolítico, primeras herramientas, arte rupestre y los grandes asentamientos humanos.",
                "status_label": "Desbloqueada · En progreso",
                "status_class": "era-status-dot--terra",
                "progress": 75,
                "progress_class": "prog-fill--terra",
                "progress_label": "9 de 12 retos completados · 75%",
                "button_label": "Continuar →",
                "button_url": "/eras",
                "button_variant": "primary",
                "image": "/static/img/stonehenge.jpg",
                "alt_text": "Stonehenge — monumentos megalíticos neolíticos",
                "error_fill": "#C8B080",
                "locked": False,
                "locked_class": "",
                "figure_class": "",
            },
            {
                "number": "II",
                "title": "Edad Antigua",
                "caption": "Fig. 2 — Las pirámides de Giza, Dinastía IV, c. 2560 a.C.",
                "description": "Mesopotamia, Egipto, Grecia clásica, Roma y el nacimiento de la filosofía occidental.",
                "status_label": "Desbloqueada · En progreso",
                "status_class": "era-status-dot--navy",
                "progress": 30,
                "progress_class": "prog-fill",
                "progress_label": "4 de 12 retos completados · 30%",
                "button_label": "Continuar →",
                "button_url": "/eras",
                "button_variant": "primary",
                "image": "/static/img/giza.jpg",
                "alt_text": "Pirámides de Giza, Antiguo Egipto",
                "error_fill": "#B0A070",
                "locked": False,
                "locked_class": "",
                "figure_class": "",
            },
            {
                "number": "III",
                "title": "Edad Media",
                "caption": "Fig. 3 — Acceso restringido · Contenido bloqueado",
                "description": "Feudalismo, cruzadas, arte gótico y el Renacimiento como punto de inflexión de la modernidad.",
                "status_label": "Bloqueada",
                "status_class": "era-status-dot--muted",
                "progress": 0,
                "progress_class": "prog-fill--terra",
                "progress_label": "0 de 12 retos · Bloqueada",
                "button_label": "Bloqueada",
                "button_url": None,
                "button_variant": "secondary",
                "image": "",
                "alt_text": "Contenido bloqueado",
                "error_fill": "#D8CEB8",
                "locked": True,
                "locked_class": "locked",
                "figure_class": "era-figure--locked",
            },
        ],
        "steps": [
            {
                "number": "01",
                "title": "Crea tu cuenta",
                "description": "Registro gratuito en menos de 60 segundos. Sin tarjeta de crédito ni compromisos.",
                "accent": False,
            },
            {
                "number": "02",
                "title": "Elige una era",
                "description": "Comienza siempre en la Prehistoria. El orden cronológico es parte del aprendizaje.",
                "accent": False,
            },
            {
                "number": "03",
                "title": "Resuelve retos",
                "description": "Análisis de fuentes primarias, preguntas contextuales y desafíos de interpretación histórica.",
                "accent": False,
            },
            {
                "number": "04",
                "title": "Evoluciona",
                "description": "Desbloquea nuevas eras, gana insignias y construye tu árbol del conocimiento histórico.",
                "accent": True,
            },
        ],
        "values": [
            {
                "image": "/static/img/gioconda.jpg",
                "alt_text": "La Gioconda, Leonardo da Vinci, c. 1503–1519",
                "caption": "Leonardo da Vinci, La Gioconda, c. 1503–1519",
                "title": "Progresión real",
                "description": "Cada nivel construye sobre el anterior. No puedes saltarte la historia, igual que no puedes saltarte el tiempo.",
                "accent_class": "value-accent-bar--terra",
                "error_fill": "#B8A090",
                "figure_class": "value-figure--gioconda",
            },
            {
                "image": "/static/img/creacion de adan.jpg",
                "alt_text": "La Creación de Adán, Miguel Ángel, c. 1512",
                "caption": "Miguel Ángel, La Creación de Adán, Capilla Sixtina, c. 1512",
                "title": "Contenido riguroso",
                "description": "Material estructurado por historiadores. Fuentes verificadas y presentadas con rigor académico en cada era.",
                "accent_class": "value-accent-bar--navy",
                "error_fill": "#C0A878",
            },
            {
                "image": "/static/img/ciriculo de avebury.jpeg",
                "alt_text": "Círculo megalítico de Avebury, Wiltshire, c. 3000 a.C.",
                "caption": "Círculo megalítico de Avebury, Wiltshire, c. 3000 a.C.",
                "title": "Logros desbloqueables",
                "description": "Cada era superada abre contenido exclusivo, insignias y acceso a los siguientes periodos de la historia humana.",
                "accent_class": "value-accent-bar--gold",
                "error_fill": "#B8A880",
            },
        ],
    }


def get_page_context(active_page: str) -> Dict[str, str]:
    return {"active_page": active_page}
